knowyourrank/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('homepage.urls')),
  path('ranking/', include('ranking.urls')),
]

ranking/urls.py
from . import views
from django.urls import path

app_name = 'ranking'

urlpatterns = [
  path('world/', views.world_ranking_list, name='world'),
  path('world-times/', views.world_times_list, name='world_times'),
  path('world-shang/', views.world_shanghai_list, name='world_shanghai'),
  path('university/', views.univ_details, name='university'),
  path('country/', views.country_ranking_list, name='country'),
  path('country-times/', views.country_times_list, name='country_times'),
  path('country-shang/', views.country_shanghai_list, name='country_shanghai'),
]

ranking/models.py
from django.db import models

# Create your models here.

ranking/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator, EmptyPage
from rdflib import Graph
from SPARQLWrapper import SPARQLWrapper, JSON

# Create your views here.
def searchWorld(system, year):
  ranking= []
  sparql = SPARQLWrapper('http://localhost:3030/university_ranking/query')
  sparql.setQuery('''
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX ex: <http://example.org/>

    SELECT ?universityName ?rank ?year
    WHERE {{
      ?university rdf:type dbo:University;
                  ex:name ?universityName;
                  ex:{0}_{1}_world_rank ?rank.
      ex:{2}_{3}_world_rank ex:year ?year.
    }}
    ORDER BY ASC (?rank)
  '''.format(year, system, year, system)
  )
  sparql.setReturnFormat(JSON)
  qres = sparql.query().convert()
  qres = qres['results']['bindings']
  for row in qres:
    datas = {}
    for key in row:
      datas[key] = row[key]['value']
    ranking.append(datas)
  return ranking

def searchCountry(system, year, country):
  ranking= []
  sparql = SPARQLWrapper('http://localhost:3030/university_ranking/query')
  sparql.setQuery('''
    PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX dbo: <http://dbpedia.org/ontology/>
    PREFIX ex: <http://example.org/>

    SELECT ?universityName ?rank ?year ?country
    WHERE {{
      ?university rdf:type dbo:University;
                  ex:name ?universityName;
                  ex:country ?country;
                  ex:{0}_{1}_world_rank ?rank.
      ex:{2}_{3}_world_rank ex:year ?year.
    FILTER (?country = "{4}")
    }}
    ORDER BY ASC (?rank)
  '''.format(year, system, year, system, country)
  )
  sparql.setReturnFormat(JSON)
  qres = sparql.query().convert()
  qres = qres['results']['bindings']
  for row in qres:
    datas = {}
    for key in row:
      datas[key] = row[key]['value']
    ranking.append(datas)
  return ranking

def world_ranking_list(request):
  year = request.GET.get('year')
  if year == None:
    year = 2012
  ranking = searchWorld('cwur', year)
  p = Paginator(ranking, 10)
  page_num = request.GET.get('page', 1)
  try:
    page = p.page(page_num)
  except EmptyPage:
    page = p.page(1)
  return render(request, 'world_cwur.html', {'ranking': page, 'cwurActive': 'active'})

def world_times_list(request):
  year = request.GET.get('year')
  if year == None:
    year = 2011
  ranking = searchWorld('times', year)
  p = Paginator(ranking, 10)
  page_num = request.GET.get('page', 1)
  try:
    page = p.page(page_num)
  except EmptyPage:
    page = p.page(1)
  return render(request, 'world_times.html', {'ranking': page, 'timesActive': 'active'})

def world_shanghai_list(request):
  year = request.GET.get('year')
  if year == None:
    year = 2005
  ranking = searchWorld('shanghai', year)
  p = Paginator(ranking, 10)
  page_num = request.GET.get('page', 1)
  try:
    page = p.page(page_num)
  except EmptyPage:
    page = p.page(1)
  return render(request, 'world_shanghai.html', {'ranking': page, 'shanghaiActive': 'active'})

def univ_details(request):
  univ = ""
  if request.method == 'POST':
    univ = request.POST.get('univ')
    special = ['of', 'and', 'in', 'for', 'on', 'de']
    univ = univ.lower().split(' ')
    univ = ' '.join([word.capitalize() if word not in special else word for word in univ])
    sparql = SPARQLWrapper('http://localhost:3030/university_ranking/query')
    sparql.setQuery('''
      PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
      PREFIX dbo: <http://dbpedia.org/ontology/>
      PREFIX ex: <http://example.org/>

      SELECT ?universityName ?cwur ?times ?shanghai ?country
      WHERE {{
        ?university rdf:type dbo:University;
                    ex:name "{0}";
                    ex:name ?universityName;
                    ex:country ?country.
        OPTIONAL {{ ?university ex:2015_cwur_world_rank ?cwur }} .
        OPTIONAL {{ ?university ex:2016_times_world_rank ?times }}  .
        OPTIONAL {{ ?university ex:2015_shanghai_world_rank ?shanghai }} .
      }}
    '''.format(univ)
    )
    sparql.setReturnFormat(JSON)
    qres = sparql.query().convert()
    qres = qres['results']['bindings']
    local = []
    for row in qres:
      datas = {}
      for key in row:
        datas[key] = row[key]['value']
      local.append(datas)
    
    sparql = SPARQLWrapper('https://dbpedia.org/sparql')
    sparql.setQuery('''
      SELECT ?univ ?abstract ?city ?mascot ?motto ?students ?link ?cityLink
      WHERE {{
        ?univ rdf:type dbo:University;
              dbp:name "{0}"@en.
        OPTIONAL {{ ?univ dbo:abstract ?abstract }}.
        OPTIONAL {{ ?univ dbo:city ?cityLink }}.
        OPTIONAL {{ ?univ dbo:motto ?motto }}.
        OPTIONAL {{ ?univ dbp:students ?students }}.
        OPTIONAL {{ ?univ foaf:isPrimaryTopicOf ?link }}.
        OPTIONAL {{ ?univ dbo:mascot ?mascot }}.
        OPTIONAL {{ ?cityLink rdfs:label ?city }} .
        FILTER (lang(?abstract) = 'en' and lang(?city)='en')
      }}
    '''.format(univ)
    )
    sparql.setReturnFormat(JSON)
    qres = sparql.query().convert()
    qres = qres['results']['bindings']
    dbpedia = []
    for row in qres:
      datas = {}
      for key in row:
        datas[key] = row[key]['value']
      dbpedia.append(datas)
    warn = ""
    if len(local) <=0 or len(dbpedia) <= 0:
      warn = "Tidak ada Data universitas"
    if warn != "":
      return render(request, 'univ_details.html', {'warn': warn})
  return render(request, 'univ_details.html', {'local': local[0], 'dbpedia': dbpedia[0]})

def country_ranking_list(request):
  year = request.GET.get('year')
  country = request.GET.get('country')
  special = ['of', 'and', 'in', 'for', 'on', 'de']
  country = country.lower().split(' ')
  country = ' '.join([word.capitalize() if word not in special else word for word in country])
  if year == None:
    year = 2012
  if country == None or country == "United States of America" or country == 'Usa':
    country = 'USA'
  ranking = searchCountry('cwur', year, country)
  p = Paginator(ranking, 10)
  page_num = request.GET.get('page', 1)
  try:
    page = p.page(page_num)
  except EmptyPage:
    page = p.page(1)
  return render(request, 'country_cwur.html', {'ranking': page, 'country': country, 'cwurActive': 'active'})

def country_times_list(request):
  year = request.GET.get('year')
  country = request.GET.get('country')
  if year == None:
    year = 2011
  if country == None or country == "United States of America" or country == 'Usa':
    country = 'USA'
  ranking = searchCountry('times', year, country)
  p = Paginator(ranking, 10)
  page_num = request.GET.get('page', 1)
  try:
    page = p.page(page_num)
  except EmptyPage:
    page = p.page(1)
  return render(request, 'country_times.html', {'ranking': page, 'country': country, 'timesActive': 'active'})

def country_shanghai_list(request):
  year = request.GET.get('year')
  country = request.GET.get('country')
  if year == None:
    year = 2005
  if country == None or country == "United States of America" or country == 'Usa':
    country = 'USA'
  ranking = searchCountry('shanghai', year, country)
  p = Paginator(ranking, 10)
  page_num = request.GET.get('page', 1)
  try:
    page = p.page(page_num)
  except EmptyPage:
    page = p.page(1)
  return render(request, 'country_shanghai.html', {'ranking': page, 'country': country, 'shanghaiActive': 'active'})

ranking/templates/country_cwur.html
{% extends 'country_rankings.html' %}
{% load static %}

{% block rank_title %} Ranking in {{ country }} {% endblock %}

{% block year %}
  <div class="univ-rank-year-container">
    <form action="{% url 'ranking:country' %}" method='GET'>
      {% csrf_token %}
      <label for="year"> Year: </label>
      <select name="year" id="rank-year">
        <option value="2012"> 2012 </option>
        <option value="2013"> 2013 </option>
        <option value="2014"> 2014 </option>
        <option value="2015"> 2015 </option>
      </select>
      <input type="hidden" name="country" value="{{ country }}">
      <div class="div-button">
        <button class='filter-button'> Filter </button>
      </div>
    </form>
  </div>
{% endblock %}
{% block ranking %}
  <div class="rankings-container">
    <table class='univ-rankings'>
      <tr>
        <th> Rank </th>
        <th> University Name </th>
        <th> Year </th>
        <th> Country </th>
        <th> Details </th>
      </tr>
      {% for row in ranking %}
        <tr>
          <td> {{ row.rank }} </td>
          <td> {{ row.universityName }} </td>
          <td> {{ row.year }} </td>
          <td> {{ row.country }} </td>
          <td align=center> 
            <form action="{% url 'ranking:university' %}" method='POST'>
              {% csrf_token %}
              <button class='filter-button view-details-button'
                type="submit" name='univ' value= "{{ row.universityName }}">View Details</button>
            </form>
          </td>
        </tr>
      {% endfor %}
      
    </table>
  </div>
  <div class="page-nav-container">
    {% if ranking.has_previous %}
      <a href="{% url 'ranking:country' %}?page={{ranking.previous_page_number}}&country={{country}}"> Previous </a>
    {% endif %}
    {% if ranking.has_next %}
      <a href="{% url 'ranking:country' %}?page={{ranking.next_page_number}}&country={{country}}"> Next </a>
    {% endif %}
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endblock %}

ranking/templates/country_rankings.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'world_rank.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}

  <div class="univ-rank-title">
    <p> {% block rank_title %}{% endblock %} </p>
  </div>
  <div class="univ-rank-nav-container">
    <div class="univ-nav {{ cwurActive }} ">
      <p> <a href="{% url 'ranking:country' %}?country={{country}}"> CWUR </a> </p>
    </div>
    <div class="univ-nav {{ timesActive }} ">
      <p> <a href="{% url 'ranking:country_times' %}?country={{country}}"> Times </a> </p>
    </div>
    <div class="univ-nav {{ shanghaiActive }} ">
      <p> <a href="{% url 'ranking:country_shanghai' %}?country={{country}}"> Shanghai </a> </p>
    </div>
  </div>
  
  {% block year %}{% endblock %}
  {% block ranking %}{% endblock %}

{% endblock %}

ranking/templates/country_shanghai.html
{% extends 'country_rankings.html' %}
{% load static %}

{% block rank_title %} Ranking in {{ country }} {% endblock %}

{% block year %}
  <div class="univ-rank-year-container">
    <form action="{% url 'ranking:country_shanghai' %}" method='GET'>
      {% csrf_token %}
      <label for="year"> Year: </label>
      <select name="year" id="rank-year">
        <option value="2005"> 2005 </option>
        <option value="2006"> 2006 </option>
        <option value="2007"> 2007 </option>
        <option value="2008"> 2008 </option>
        <option value="2009"> 2009 </option>
        <option value="2010"> 2010 </option>
        <option value="2011"> 2011 </option>
        <option value="2012"> 2012 </option>
        <option value="2013"> 2013 </option>
        <option value="2014"> 2014 </option>
        <option value="2015"> 2015 </option>
      </select>
      <input type="hidden" name="country" value="{{ country }}">
      <div class="div-button">
        <button class='filter-button'> Filter </button>
      </div>
    </form>
  </div>
{% endblock %}
{% block ranking %}
  <div class="rankings-container">
    <table class='univ-rankings'>
      <tr>
        <th> Rank </th>
        <th> University Name </th>
        <th> Year </th>
        <th> Country </th>
        <th> Details </th>
      </tr>
      {% for row in ranking %}
        <tr>
          <td> {{ row.rank }} </td>
          <td> {{ row.universityName }} </td>
          <td> {{ row.year }} </td>
          <td> {{ row.country }} </td>
          <td align=center> 
            <form action="{% url 'ranking:university' %}" method='POST'>
              {% csrf_token %}
              <button class='filter-button view-details-button'
                type="submit" name='univ' value= "{{ row.universityName }}">View Details</button>
            </form>
          </td>
        </tr>
      {% endfor %}
      
    </table>
  </div>
  <div class="page-nav-container">
    {% if ranking.has_previous %}
      <a href="{% url 'ranking:country_shanghai' %}?page={{ranking.previous_page_number}}&country={{country}}"> Previous </a>
    {% endif %}
    {% if ranking.has_next %}
      <a href="{% url 'ranking:country_shanghai' %}?page={{ranking.next_page_number}}&country={{country}}"> Next </a>
    {% endif %}
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endblock %}

ranking/templates/country_times.html
{% extends 'country_rankings.html' %}
{% load static %}

{% block rank_title %} Ranking in {{ country }} {% endblock %}

{% block year %}
  <div class="univ-rank-year-container">
    <form action="{% url 'ranking:country_times' %}" method='GET'>
      {% csrf_token %}
      <label for="year"> Year: </label>
      <select name="year" id="rank-year">
        <option value="2011"> 2011 </option>
        <option value="2012"> 2012 </option>
        <option value="2013"> 2013 </option>
        <option value="2014"> 2014 </option>
        <option value="2015"> 2015 </option>
        <option value="2016"> 2016 </option>
      </select>
      <input type="hidden" name="country" value="{{ country }}">
      <div class="div-button">
        <button class='filter-button'> Filter </button>
      </div>
    </form>
  </div>
{% endblock %}
{% block ranking %}
  <div class="rankings-container">
    <table class='univ-rankings'>
      <tr>
        <th> Rank </th>
        <th> University Name </th>
        <th> Year </th>
        <th> Country </th>
        <th> Details </th>
      </tr>
      {% for row in ranking %}
        <tr>
          <td> {{ row.rank }} </td>
          <td> {{ row.universityName }} </td>
          <td> {{ row.year }} </td>
          <td> {{ row.country }} </td>
          <td align=center> 
            <form action="{% url 'ranking:university' %}" method='POST'>
              {% csrf_token %}
              <button class='filter-button view-details-button'
                type="submit" name='univ' value= "{{ row.universityName }}">View Details</button>
            </form>
          </td>
        </tr>
      {% endfor %}
      
    </table>
  </div>
  <div class="page-nav-container">
    {% if ranking.has_previous %}
      <a href="{% url 'ranking:country_times' %}?page={{ranking.previous_page_number}}&country={{country}}"> Previous </a>
    {% endif %}
    {% if ranking.has_next %}
      <a href="{% url 'ranking:country_times' %}?page={{ranking.next_page_number}}&country={{country}}"> Next </a>
    {% endif %}
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endblock %}

ranking/templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="univ-rank-title">
        <p> {% block rank_title %}{% endblock %} </p>
    </div>
    {% block university %}{% endblock %}

{% endblock %}

ranking/templates/rankings.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'world_rank.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
{% endblock %}

{% block content %}

  <div class="univ-rank-title">
    <p> {% block rank_title %}{% endblock %} </p>
  </div>

  <div class="univ-rank-nav-container">
    <div class="univ-nav {{ cwurActive }} ">
      <p> <a href="{% url 'ranking:world' %}"> CWUR </a> </p>
    </div>
    <div class="univ-nav {{ timesActive }}">
      <p> <a href="{% url 'ranking:world_times' %}"> Times </a> </p>
    </div>
    <div class="univ-nav {{ shanghaiActive}}">
      <p> <a href="{% url 'ranking:world_shanghai' %}"> Shanghai </a> </p>
    </div>
  </div>
  
  {% block year %}{% endblock %}
  {% block ranking %}{% endblock %}

{% endblock %}

ranking/templates/univ_details.html
{% extends 'details.html' %}
{% load static %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'university.css' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Mulish&display=swap" rel="stylesheet">
{% endblock %}

{% block rank_title %} {{ local.universityName }} {% endblock %}

{% block university %}
{% if warn %}
 <p style="text-align: center;"> No University Details </p>
 <div class="div-button">
  <a href="/"><button class='back-button'> Back to Homepage </button></a>
</div>
{% else %}
  <div class="all-univ-container">
    <table class="univ-container">
      <tr>
        <th align=left> Name : </th>
        <td> <a href="{{ dbpedia.univ }}"> {{ local.universityName }} </a> </th>
      </tr>
      <tr>
        <th align=left> About : </th>
        <td> {{ dbpedia.abstract }} </th>
      </tr>
      <tr>
        <th align=left> Country : </th>
        <td> {{ local.country }} </th>
      </tr>
      <tr>
        <th align=left> City : </th>
        <td> <a href="{{ dbpedia.cityLink }}"> {{ dbpedia.city }} </a> </th>
      </tr>
      <tr>
        <th align=left> CWUR Ranking : </th>
        {% if local.cwur %}
          <td> #{{ local.cwur }} (2015) </th>
        {% else %}
          <td> Unknown </th>
        {% endif %}
      </tr>
      <tr>
        <th align=left> Times Ranking : </th>
        {% if local.times %}
          <td> #{{ local.times }} (2016) </th>
        {% else %}
          <td> Unknown </th>
        {% endif %}
      </tr>
      <tr>
        <th align=left> Shanghai Ranking : </th>
        {% if local.shanghai %}
          <td> #{{ local.shanghai }} (2015) </th>
        {% else %}
          <td> Unknown </th>
        {% endif %}
      </tr>
      <tr>
        <th align=left> Mascott : </th>
        {% if dbpedia.mascot %}
          <td> {{ dbpedia.mascot }} </th>
        {% else %}
          <td> Unknown </td>
        {% endif %}
      </tr>
      <tr>
        <th align=left> Motto : </th>
        {% if dbpedia.motto %}
          <td> {{ dbpedia.motto }} </th>
        {% else %}
          <td> Unknown </td>
        {% endif %}
      </tr>
      <tr>
        <th align=left> Number of Students : </th>
        {% if dbpedia.students %}
          <td> {{ dbpedia.students }} </th>
        {% else %}
          <td> Unknown </td>
        {% endif %}
      </tr>
      <tr>
        <th align=left> Wikipedia : </th>
        <td> <a href="{{ dbpedia.link }}" target="_blank"> {{ local.universityName }} </a> </th>
      </tr>
    </table>
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endif %}
{% endblock %}

ranking/templates/world_cwur.html
{% extends 'rankings.html' %}
{% load static %}

{% block rank_title %} CWUR World Ranking {% endblock %}

{% block year %}
  <div class="univ-rank-year-container">
    <form action="{% url 'ranking:world' %}" method='GET'>
      {% csrf_token %}
      <label for="year"> Year: </label>
      <select name="year" id="rank-year">
        <option value="2012"> 2012 </option>
        <option value="2013"> 2013 </option>
        <option value="2014"> 2014 </option>
        <option value="2015"> 2015 </option>
      </select>
      <div class="div-button">
        <button class='filter-button'> Filter </button>
      </div>
    </form>
  </div>
{% endblock %}
{% block ranking %}
  <div class="rankings-container">
    <table class='univ-rankings'>
      <tr>
        <th> Rank </th>
        <th> University Name  </th>
        <th> Year </th>
        <th> Details </th>
      </tr>
      {% for row in ranking %}
        <tr>
          <td> {{ row.rank }} </td>
          <td > {{ row.universityName }} </td>
          <td align=center> {{ row.year }} </td>
          <td align=center> <form action="{% url 'ranking:university' %}" method='POST'>
                {% csrf_token %}
                <button class='filter-button view-details-button' type="submit" name='univ' value= "{{ row.universityName }}">View Details</button>
                </form>
          </td>
        </tr>
      {% endfor %}
      
    </table>
  </div>

  <div class="page-nav-container">
    {% if ranking.has_previous %}
      <a href="{% url 'ranking:world' %}?page={{ranking.previous_page_number}}"> Previous </a>
    {% endif %}
    {% if ranking.has_next %}
      <a href="{% url 'ranking:world' %}?page={{ranking.next_page_number}}"> Next </a>
    {% endif %}
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endblock %}

ranking/templates/world_shanghai.html
{% extends 'rankings.html' %}
{% load static %}

{% block rank_title %} Shanghai World Ranking {% endblock %}

{% block year %}
  <div class="univ-rank-year-container">
    <form action="{% url 'ranking:world_shanghai' %}" method='GET'>
      {% csrf_token %}
      <label for="year"> Year: </label>
      <select name="year" id="rank-year">
        <option value="2005"> 2005 </option>
        <option value="2006"> 2006 </option>
        <option value="2007"> 2007 </option>
        <option value="2008"> 2008 </option>
        <option value="2009"> 2009 </option>
        <option value="2010"> 2010 </option>
        <option value="2011"> 2011 </option>
        <option value="2012"> 2012 </option>
        <option value="2013"> 2013 </option>
        <option value="2014"> 2014 </option>
        <option value="2015"> 2015 </option>
      </select>
      <div class="div-button">
        <button class='filter-button'> Filter </button>
      </div>
    </form>
  </div>
{% endblock %}

{% block ranking %}
  <div class="rankings-container">
    <table class='univ-rankings'>
      <tr>
        <th> Rank </th>
        <th> University Name </th>
        <th> Year </th>
        <th> Details </th>
      </tr>
      {% for row in ranking %}
        <tr>
          <td> {{ row.rank }} </td>
          <td> {{ row.universityName }} </td>
          <td align=center> {{ row.year }} </td>
          <td align=center> <form action="{% url 'ranking:university' %}" method='POST'>
                {% csrf_token %}
                <button class='filter-button view-details-button' type="submit" name='univ' value= "{{ row.universityName }}">View Details</button>
                </form>
          </td>
        </tr>
      {% endfor %}
      
    </table>
  </div>

  <div class="page-nav-container">
    {% if ranking.has_previous %}
      <a href="{% url 'ranking:world_shanghai' %}?page={{ranking.previous_page_number}}"> Previous </a>
    {% endif %}
    {% if ranking.has_next %}
      <a href="{% url 'ranking:world_shanghai' %}?page={{ranking.next_page_number}}"> Next </a>
    {% endif %}
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endblock %}

ranking/templates/world_times.html
{% extends 'rankings.html' %}
{% load static %}

{% block rank_title %} Times World Ranking {% endblock %}

{% block year %}
  <div class="univ-rank-year-container">
    <form action="{% url 'ranking:world_times' %}" method='GET'>
      {% csrf_token %}
      <label for="year"> Year: </label>
      <select name="year" id="rank-year">
        <option value="2011"> 2011 </option>
        <option value="2012"> 2012 </option>
        <option value="2013"> 2013 </option>
        <option value="2014"> 2014 </option>
        <option value="2015"> 2015 </option>
        <option value="2016"> 2016 </option>
      </select>
      <div class="div-button">
        <button class='filter-button'> Filter </button>
      </div>
    </form>
  </div>
{% endblock %}

{% block ranking %}
  <div class="rankings-container">
    <table class='univ-rankings'>
      <tr>
        <th> Rank </th>
        <th> University Name </th>
        <th> Year </th>
        <th> Details </th>
      </tr>
      {% for row in ranking %}
        <tr>
          <td> {{ row.rank }} </td>
          <td> {{ row.universityName }} </td>
          <td align=center> {{ row.year }} </td>
          <td align=center> <form action="{% url 'ranking:university' %}" method='POST'>
                {% csrf_token %}
                <button class='filter-button view-details-button' type="submit" name='univ' value= "{{ row.universityName }}">View Details</button>
                </form>
          </td>
        </tr>
      {% endfor %}
      
    </table>
  </div>

  <div class="page-nav-container">
    {% if ranking.has_previous %}
      <a href="{% url 'ranking:world_times' %}?page={{ranking.previous_page_number}}"> Previous </a>
    {% endif %}
    {% if ranking.has_next %}
      <a href="{% url 'ranking:world_times' %}?page={{ranking.next_page_number}}"> Next </a>
    {% endif %}
  </div>
  <div class="div-button">
    <a href="/"><button class='back-button'> Back to Homepage </button></a>
  </div>
{% endblock %}